### ISSUE TITLE
https not working

### ISSUE THREAD

**Issue by superflay123** [sebastienheyd/docker-self-signed-proxy-companion#10]
hello, i am trying to run wordpress docker on a server on a local network. I use your reverse proxy but I manage to make WordPress work only on port 80 when I try to access WordPress through https I only see Unable to connect

docker file
version: '3.3'

services:

  db:
    container_name: ${CONTAINER_DB_NAME}
    image: ${DB_IMAGE:-mariadb}:${DB_VERSION:-latest}
    restart: unless-stopped
    volumes:
      #- /srv/www/${DOMAINS}/db_data:/var/lib/mysql
      - ./database:/var/lib/mysql
      - ./mysqldumps/backup.sql.gz:/docker-entrypoint-initdb.d/backup.sql.gz
    environment:
      #MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wp:
    container_name: ${CONTAINER_SITE_NAME}
    #build: .
    image: ${SITE_IMAGE:-wordpress}:${SITE_VERSION:-latest}
    depends_on:
      - db
    restart: unless-stopped
    volumes:
     # - ./theme:/var/www/html/wp-content/themes/${WP_THEME}:rw
     # - ./plugin:/var/www/html/wp-content/plugins/${WP_PLUGIN}:rw
       - ./site/wp-content:/var/www/html/wp-content:rw
     #  - /srv/www/${DOMAINS}/wp_content:/var/www/html/wp-content:rw
       - ./init/prep.sh:/usr/local/bin/prep.sh
     #  - ./ssl:/etc/letsencrypt
    environment:
      WORDPRESS_DB_HOST: ${CONTAINER_DB_NAME}:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_DEBUG: ${wp_debug_mode}
      DISABLED_PLUGINS: ${wp_plugins_to_disable}
      VIRTUAL_HOST: ${DOMAINS}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_TEST: 'false'
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE:-200k}
networks:
  default:
    external:
      name: ${NETWORK}

please help

**Comment by sebastienheyd** [comment]
As described in the [readme](https://github.com/sebastienheyd/docker-self-signed-proxy-companion/blob/master/README.md), you have to set `SELF_SIGNED_HOST` in addition to `VIRTUAL_HOST`
