### ISSUE TITLE
bad gateway for every wordpress where deploying

### ISSUE THREAD

**Issue by superflay123** [sebastienheyd/docker-self-signed-proxy-companion#11]
hi, i now setup correctly your nginx-proxy with companion but when deploying worpress site i get 502 Bad Gateway  my domain is kasha.com it si use for local development and i set  correct  SELF_SIGNED_HOST: "kasha.com" here is docker compose yml 
in /etc/hosts i set 127.0.0.1 kasha.com can you tell me where i wrong

version: '3.3'

services:

  db:
    container_name: ${CONTAINER_DB_NAME}
    image: ${DB_IMAGE:-mariadb}:${DB_VERSION:-latest}
    restart: unless-stopped
    volumes:
      #- /srv/www/${DOMAINS}/db_data:/var/lib/mysql
      - ./database:/var/lib/mysql
      - ./mysqldumps/backup.sql.gz:/docker-entrypoint-initdb.d/backup.sql.gz
    environment:
      #MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wp:
    container_name: ${CONTAINER_SITE_NAME}
    ports: 
      - "8080:80"
      - "8443:443"
    #build: .
    image: ${SITE_IMAGE:-wordpress}:${SITE_VERSION:-latest}
    depends_on:
      - db
    restart: unless-stopped
    volumes:
     # - ./theme:/var/www/html/wp-content/themes/${WP_THEME}:rw
     # - ./plugin:/var/www/html/wp-content/plugins/${WP_PLUGIN}:rw
       - ./site/wp-content:/var/www/html/wp-content
     #  - /srv/www/${DOMAINS}/wp_content:/var/www/html/wp-content:rw
       - ./init/prep.sh:/usr/local/bin/prep.sh
    environment:
      WORDPRESS_DB_HOST: ${CONTAINER_DB_NAME}:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_DEBUG: ${wp_debug_mode}
      DISABLED_PLUGINS: ${wp_plugins_to_disable}
      VIRTUAL_HOST: ${DOMAINS}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      SELF_SIGNED_HOST: "kasha.com"
      # LETSENCRYPT_HOST: ${DOMAINS}
      #LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      #LETSENCRYPT_TEST: 'true'
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE:-200k}

networks:
  default:
    external:
      name: ${NETWORK}

**Comment by sebastienheyd** [comment]
Remove VIRTUAL_PORT.

This is not an issue with `docker-self-signed-proxy-companion` and stop opening issues only for help, this is not a helpdesk, thank you
