### ISSUE TITLE
.well-known warnings from Nextcloud

### ISSUE THREAD

**Issue by oleua** [sebastienheyd/docker-self-signed-proxy-companion#3]
Hi!

I have installed your docker image. In the Nextcloud overview check I am getting warnings:
```
Your web server is not properly set up to resolve "/.well-known/caldav".
Your web server is not properly set up to resolve "/.well-known/carddav".
```
Please, recommend, what may be done?

**Comment by sebastienheyd** [comment]
Hi,

I think this is a Nextcloud issue with using the nginx proxy. The proxy companion does not use the .well-known folder like LetsEncrypt.

Have a look to these topics : 

- https://help.nextcloud.com/t/solved-well-known-caldav-check-in-13-0-7-explained/38957/6
- https://help.nextcloud.com/t/warning-your-web-server-is-not-properly-set-up-to-resolve-well-known-caldav/63715
