### ISSUE TITLE
add support for arm64

### ISSUE THREAD

**Issue by Ivorius** [sebastienheyd/docker-self-signed-proxy-companion#4]
I would like use this on mac M1, but it is not supported arm64.

Logs from container
standard_init_linux.go:228: exec user process caused: exec format error

Info uname -a
Linux ubuntu 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:56:23 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

**Comment by sebastienheyd** [comment]
I don't have an amd64 architecture to test, but have you tried to build for arm64 ?

Clone the repository to a folder, go into it and run : 

`docker build -t sebastienheyd/self-signed-proxy-companion .`

If it does not work try to change `FROM alpine:latest`to `FROM arm64v8/alpine:latest` in `Dockerfile` and build again

**Comment by Ivorius** [comment]
I made arm64 branch here https://github.com/Ivorius/docker-self-signed-proxy-companion/tree/arm64

**Comment by sebastienheyd** [comment]
I just added a way to build directly with the architecture you need : 

https://github.com/sebastienheyd/docker-self-signed-proxy-companion#architecture

**Comment by sebastienheyd** [comment]
See #7 

Build is now multi-arch
