### ISSUE TITLE
Chrome allow insecure localhost

### ISSUE THREAD

**Issue by vordimous** [sebastienheyd/docker-self-signed-proxy-companion#6]
Just found your project and you are a lifesaver. I am working in chrome on a mac and as of Chrome 94, I needed to set the `chrome://flags/#allow-insecure-localhost` to allow the usage of these self-signed certs. I just wanted to create this issue for you to update the README or for anyone else looking for a solution.

**Comment by sebastienheyd** [comment]
Thanks for your comment !

This is a solution, but have you tried to import the CA certificate to trust the generated self signed certificates ? This is a cleaner solution.

You will find a file `ca.crt` in the `certs` folder, this is your CA certificate.

- Go to : `chrome://settings/certificates`
- Go to `Authorities` and import `ca.crt`
- Check `Trust the CA to identify websites`

After that, your self signed certificates will be trusted.

However I will add your solution in the readme, it can be a faster solution.

**Comment by vordimous** [comment]
I did add the `ca.crt`. Chrome just prompts mac to open Keychain Access instead of having the `chrome://settings/certificates` page.

![image](https://user-images.githubusercontent.com/3012311/137493969-94592a84-1070-4740-92dc-f8b99fa83453.png)

I'm not sure if this is specific to me or to all Mac:Chrome users. But if I only import the cert Chrome is still mad that it is self signed until I update the above flag.

**Comment by waffledonkey** [comment]
You have to add the ca.crt to the mac's keychain, then double-click it and under Trust you have to _minimally_ set Secure Sockets Layer (SSL) to Always Trust it.  Enabling only SSL will give you a happy 'lock' but inspecting the cert it will say it's untrusted.  If you set it to trust everything it won't do that, but I don't know which combination of protocols will make it happy without enabling everything.  Once trusted, attempt to close the keychain window and you'll be asked to authenticate the change. You may need to restart the browser, but I don't have to disable QUIC or allow insecure certs in chrome://flags.

I believe this is _partially_ related to the [author's comment on my issue](https://github.com/sebastienheyd/docker-self-signed-proxy-companion/issues/1#issuecomment-831090095) RE: cert expirations.  By setting the certificate to be trusted in keychain, maybe Chrome is perceiving it as trusted and thus enforcing the 398 day limit.

**Comment by uuf6429** [comment]
Hey, just a small follow up on the two solutions mentioned above, is there some way to do it programmatically? I'd like to build a docker image that accepts a self-signed cert by default.
