### ISSUE TITLE
FR: build for arm64 / apple silicon

### ISSUE THREAD

**Issue by irmantas** [sebastienheyd/docker-self-signed-proxy-companion#7]
Feature request

Hi currently this locked only for `amd64` architecture. As macos with apple silicon is gaining some popularity among developers (especially within web developers) it would be nice to have this image build for that architecture.

**Comment by sebastienheyd** [comment]
Hi,

I just pushed a multi-architecture version, can you tell me if it works?

**Comment by irmantas** [comment]
Wow that was fast. And it works with no issues. Thank you very much @sebastienheyd !
